// <auto-generated />
namespace dreamlet.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m2_AddColumn_LikeCount_ToTable_DreamTermStatistic_And_Default_Values : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m2_AddColumn_LikeCount_ToTable_DreamTermStatistic_And_Default_Values));
        
        string IMigrationMetadata.Id
        {
            get { return "201701142322312_m2_AddColumn_LikeCount_ToTable_DreamTermStatistic_And_Default_Values"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
